POST http://localhost:3001/api/notes/
Content-Type: application/json

{
    "content": "hola mis amigos",
    "userId": "60db8cfa8f2f4b28942c9ecd",
    "important":  true
}

### error for a missing note
POST http://localhost:3001/api/notes/
Content-Type: application/json

{
}
