POST http://localhost:3001/api/notes/
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZGI4Y2ZhOGYyZjRiMjg5NDJjOWVjZCIsInVzZXJuYW1lIjoiRGFuaWVsIiwiaWF0IjoxNjI1MTc3MzI2fQ.SDu8DaJ-l3YkiaJMYweAdUBLOEVKCKuPX6FdQpAU0nI

{
    "content": "con token",
    "important":  true
}

### error for a missing note
POST http://localhost:3001/api/notes/
Content-Type: application/json

{
}
